Expand the README
nextcloud/integration_google pull request #20
Opened 2020-10-31 03:31 UTC by strugee

In particular, add a note that setup instructions are in the app itself,
since they're kind of deemphasized in the UI. This confused me for a
moment when I didn't notice them, went looking for instructions in the
README instead, and found nothing.

Installation instructions shamelessly cribbed from nextcloud/photos.

2020-10-31 12:35 UTC, eneiluj requested changes
Yay thanks! A few remarks.

2020-10-31 12:35 UTC, eneiluj commented on README.md
> +In your Nextcloud, simply enable the Google Integration app through the Apps management. The Google Integration app is only included in Nextcloud v20 and higher.
```suggestion
In your Nextcloud, simply enable the Google Integration app through the Apps management. The Google Integration app is only included in Nextcloud 20 and higher.
```

2020-10-31 12:35 UTC, eneiluj commented on README.md
> +The app needs some setup in the Google API Console in order to work. To do this, go to Settings > Administration > Connected accounts and follow the instructions under "Google integration".
It's not clear that your first talk about the google side and then the Nextcloud settings.

```suggestion
The app needs some setup in the Google API Console in order to work. To do this, go to Nextcloud Settings > Administration > Connected accounts and follow the instructions of "Google integration" section.
```

2022-12-21 12:10 UTC, julien-nc commented
Manually merged with small adjustments.

2022-12-21 12:10 UTC, closed without merging

2022-12-21 21:38 UTC, strugee commented
Ack, sorry I never got around to followup work here. Thank you :-)